spring:
  datasource:
    url: jdbc:mysql://localhost:3306/covid-db
    username: root
    password: root
  jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      open-in-view: false
      show-sql: true
      hibernate.ddl-auto: update
  liquibase:
    enabled: false
logging:
  level:
    org:
      springframework:
        security: DEBUG
